### ISSUE TITLE
убрать из релиза программы информацию об исправленных багах и об изменениях в принципе (version changes) во вкладке "О приложении"

### ISSUE THREAD

**Issue by otcheski** [itregsiamoil/SiamCross#52]

**Comment by otcheski** [comment]
После того как уберешь, нужно будет через Фомина обновить релиз на всех ресурсах куда он его выложил. Не нужно чтобы пользователь это видел.

**Comment by itregsiamoil** [comment]
По умолчанию история изменений должна быть скрыта. При пятикратном нажатии на пункт с версией - выводить диалог с перечнем изменений.
