### ISSUE TITLE
сделать кнопку подключения

### ISSUE THREAD

**Issue by otcheski** [itregsiamoil/SiamCross#81]
когда подключаешь прибор, появляется окно select device, и не понятно куда тыкать, кроме как Cancel. надо либо сделать кнопку Подключить, либо ОК. сейчас специальный человек делал сопряжение и не мог понять куда нажимать. версия 2.6.1. и перевести на русский язык надо всё

**Comment by itregsiamoil** [comment]
исправлена надпись на "Добавить устройство (нажмите для подтверждения)"
https://github.com/itregsiamoil/SiamCross/commit/cd94c7926e08f6dfc6bed13b97f72e88b58f9b66
