### ISSUE TITLE
Ошибка при отображении графика (результат замера) ДУ и ДУА

### ISSUE THREAD

**Issue by otcheski** [itregsiamoil/SiamCross#82]
На графике (эхограмме) при замере уровня до 6000 м. по оси x отображается 3000 м. как крайняя точка. Нужно, чтобы 6000 м. отображалось, а то пользователь будет смущаться и думать, что 3000 м. замерил.

**Comment by itregsiamoil** [comment]
исправлено  в v2.11.0
